name: "Show Directory and Greet"
description: "Display current directory and greet"

runs:
  using: 'composite'
  steps:
    - name: Show Current Directory
      run: |
        echo "Current Directory: $(pwd)"
    - name: Greet
      run: echo "Hello from the Action!"
